"""Parse glossary.md into glossary-data.js for the search page.

Run this whenever glossary.md changes:
    python build_search_data.py

It produces glossary-data.js (a `window.GLOSSARY = [...]` blob the page loads via a
<script> tag — no server/fetch needed, works on GitHub Pages and from a local file).
"""

import json
import re
from pathlib import Path

HERE = Path(__file__).parent
SRC = HERE / "glossary.md"
OUT = HERE / "glossary-data.js"

SECTION_RE = re.compile(r"^##\s+(\d+)\.\s+(.+?)\s*$")
TERM_RE = re.compile(r"^###\s+(.+?)\s*$")
FIELD_RE = re.compile(r"^- \*\*(.+?):\*\*\s*(.*)$")

# Map each markdown field label -> JSON key
FIELD_KEYS = {
    "Definition": "definition",
    "When to use": "when",
    "Pitfalls": "pitfalls",
    "Example": "example",
    "Source": "source",
}


def clean_term(name: str) -> str:
    # drop trailing italic notes like *(legacy — see note)* and backticks
    name = re.sub(r"\s*\*\(.*?\)\*\s*$", "", name)
    return name.strip()


def parse():
    entries = []
    section_num = section_name = None
    cur = None
    for raw in SRC.read_text(encoding="utf-8").splitlines():
        sm = SECTION_RE.match(raw)
        if sm:
            section_num, section_name = int(sm.group(1)), sm.group(2)
            cur = None
            continue
        tm = TERM_RE.match(raw)
        if tm:
            name = tm.group(1).strip()
            if section_num is None or name.lower() == "contents":
                cur = None
                continue
            cur = {
                "term": clean_term(name),
                "raw_term": name,
                "section_num": section_num,
                "section": section_name,
                "definition": "", "when": "", "pitfalls": "", "example": "", "source": "",
            }
            entries.append(cur)
            continue
        if cur is not None:
            fm = FIELD_RE.match(raw)
            if fm and fm.group(1) in FIELD_KEYS:
                cur[FIELD_KEYS[fm.group(1)]] = fm.group(2).strip()
    return entries


def main():
    entries = parse()
    # stable order; attach an id
    for i, e in enumerate(entries):
        e["id"] = i
    OUT.write_text(
        "// Auto-generated by build_search_data.py — do not edit by hand.\n"
        "window.GLOSSARY = " + json.dumps(entries, ensure_ascii=False, indent=1) + ";\n",
        encoding="utf-8",
    )
    sections = sorted({(e["section_num"], e["section"]) for e in entries})
    print(f"Wrote {OUT.name}: {len(entries)} entries across {len(sections)} sections.")
    for n, name in sections:
        cnt = sum(1 for e in entries if e["section_num"] == n)
        print(f"  {n}. {name} ({cnt})")


if __name__ == "__main__":
    main()
